### ISSUE TITLE
Service Catalog Framework Multi-Region deployment failed using latest version

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-factory#273]
Service catalog factory 0.81.0 is used in Development account, and I could deploy AWS services to multiple accounts and regions successfully.
In production, service catalog factory used 0.83.0 as latest version. Deployed AWS services to default region across accounts successfully. 
However, enabling multi region in service catalog factory initialization stack, generates duplicate auto-generated pipelines and service catalog pipeline itself failed.
Service catalog puppet failed with Parameter Exception. 
ServiceCatalog Factory github latest release is 0.82, but factory picked default version as 0.83.0.

# Steps to reproduce
I have upgraded the version of development account manually to recreate the same issue.  
I ran into same issue for both 0.82 and 0.83. 

# Expected results
Latest version should support multi-region deployment without recreating or duplicating existing pipelines. Service catalog factory and Service catalog manifest should be successful.

# Actual results
Log snippets - 

> 1. Service Catalog factory pipeline error:

<img width="1571" alt="Screen Shot 2022-08-04 at 7 27 14 PM" src="https://user-images.githubusercontent.com/37020616/182972295-983573c7-8f8d-4522-9d88-2d60daf03885.png">

> 2. Service Catalog factory auto-generate pipeline for each aws service error: 

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/37020616/182972451-89961c22-8ad2-4dfb-947b-223d5ee09d30.png">

> 3. Service Catalog Puppet pipeline error:  

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/37020616/182975085-7ae2f3aa-7724-43d7-a2ed-bdc27193d2f2.png">

> 4. Service Catalog github latest version is not 0.83.0 

<img width="956" alt="image" src="https://user-images.githubusercontent.com/37020616/182976373-eee5a125-aaf0-4fe8-bd67-a3ff42fcd672.png">

**Comment by eamonnfaherty** [comment]
CreateVersionPipelineTemplateTask is not being run.  This is causing the product ids file not to be written

**Comment by eamonnfaherty** [comment]
fixed in 0.83.0

**Comment by shydhanya** [comment]
@eamonnfaherty Upgraded factory to version 0.84 and received below error while executing factory pipeline. THis time it didnt create duplicate product pipelines. 

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/37020616/183647700-b26d5068-2f63-48ac-8434-ea8bb4b893e6.png">

**Comment by shydhanya** [comment]
Could you please, above issue still exists in 0.83 as well as 0.84?
